import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";
import prettier from "eslint-config-prettier";

/**
 * Tailwind only generates classes it can see as complete literals in the
 * source. A class finished at runtime — `h-[${pages * 100}vh]`, `from-${c}` —
 * is invisible to it and gets purged, so the style silently does not exist in
 * the build. This has shipped three separate bugs in this repo: the timeline
 * rail rendered invisible, the portfolio section lost its height and its
 * horizontal scroll bled into the next section.
 *
 * Only the *partial* form is flagged, where the interpolation completes a
 * class name. A whole class passed in (`${className}`) is normal and safe.
 */
const tailwindRuntimeClasses = {
  rules: {
    "no-runtime-class": {
      meta: {
        type: "problem",
        docs: {
          description:
            "Disallow completing a Tailwind class name with an interpolation",
        },
        schema: [
          {
            type: "object",
            properties: {
              // Prefixes that are selector hooks rather than Tailwind
              // utilities, e.g. `tab-${id}` used by a querySelector.
              allow: { type: "array", items: { type: "string" } },
            },
            additionalProperties: false,
          },
        ],
        messages: {
          runtime:
            "Tailwind cannot see this class and will purge it. Use an inline style, or map the value to whole literal class names.",
        },
      },
      create(context) {
        // A quasi that ends mid-token: "h-[", "from-", "md:w-".
        const PARTIAL = /[\w:)\]-]*[-[]$/;
        const allow = context.options[0]?.allow ?? [];
        // A literal inside a cn() inside a className matches both selectors.
        const seen = new Set();

        const check = (node) => {
          if (seen.has(node)) return;
          seen.add(node);
          node.quasis.forEach((quasi, index) => {
            if (index === node.quasis.length - 1) return;
            const raw = quasi.value.raw;
            if (!PARTIAL.test(raw)) return;
            // The token this interpolation completes, e.g. "tab-".
            const token = raw.slice(raw.lastIndexOf(" ") + 1);
            if (allow.some((prefix) => token.startsWith(prefix))) return;
            context.report({
              node: node.expressions[index] ?? node,
              messageId: "runtime",
            });
          });
        };

        return {
          'JSXAttribute[name.name="className"] TemplateLiteral': check,
          "CallExpression[callee.name=/^(cn|cva|clsx|twMerge)$/] TemplateLiteral":
            check,
        };
      },
    },
  },
};

export default tseslint.config(
  {
    ignores: [
      "dist",
      "coverage",
      "playwright-report",
      "test-results",
      "blob-report",
      ".playwright-mcp",
      "public",
    ],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
      tailwind: tailwindRuntimeClasses,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "@typescript-eslint/no-unused-vars": [
        "error",
        { varsIgnorePattern: "^[A-Z_]", argsIgnorePattern: "^_" },
      ],
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      // `tab-${id}` is a gsap/querySelector hook defined in index.css, not a
      // Tailwind utility, so it is safe from purging.
      "tailwind/no-runtime-class": ["error", { allow: ["tab-"] }],
    },
  },
  {
    // Generated by gltfjsx; regenerating them is the way to change them.
    files: ["src/components/models/*.tsx"],
    rules: {
      "tailwind/no-runtime-class": "off",
    },
  },
  {
    // Playwright fixtures call `use(...)`, which the react-hooks plugin reads
    // as React 19's `use` hook. None of this directory is React.
    files: ["tests/**/*.ts"],
    rules: {
      "react-hooks/rules-of-hooks": "off",
      "react-refresh/only-export-components": "off",
    },
  },
  // Last: turns off every rule that would fight Prettier.
  prettier
);
