/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cleats.glb
Author: neurodriguez (https://sketchfab.com/neurodriguez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/adidas-predator-precision-25-year-david-beckham-38852558463540ccb58f04ef21602ea1
Title: Adidas Predator Precision 25 Year David Beckham
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import type { ThreeElements } from '@react-three/fiber'
import { assetsPaths } from '../../constants';

type GroupProps = ThreeElements['group'];

type GLTFResult = {
  nodes: Record<string, THREE.Mesh>;
  materials: Record<string, THREE.MeshStandardMaterial>;
};

export function Cleats(props: GroupProps) {
  const { nodes, materials } = useGLTF(assetsPaths.models.hero.cleats) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Material} rotation={[-1.169, 0.282, 0.224]} scale={0.425} />
    </group>
  )
}

useGLTF.preload(assetsPaths.models.hero.cleats)
