/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 dumbbell.glb 
Author: tadeus (https://sketchfab.com/tadeus)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dumbbell-2835f3bdc79a4e46aaf309cde977861c
Title: Dumbbell
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { forwardRef } from 'react'

export const Dumbbell = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF('/models/hero/dumbbell.glb')
  return (
    <group {...props} dispose={null} ref={ref}>
      <group position={[-135.816, -9.227, 126.589]} rotation={[-Math.PI, 0, Math.PI / 2]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-169.213, 160.036, -33.683]} rotation={[2.555, 0.704, -1.879]} scale={[100, 61.985, 61.985]}>
            <mesh geometry={nodes.Cylinder_metal001_0.geometry} material={materials['metal.001']} />
            <mesh geometry={nodes.Cylinder_metal002_0.geometry} material={materials['metal.002']} />
            <mesh geometry={nodes.Cylinder_Material004_0.geometry} material={materials['Material.004']} />
          </group>
          <mesh geometry={nodes.Circle_metal_0.geometry} material={materials.metal} position={[-169.357, 160.13, -33.541]} rotation={[2.555, 0.704, -1.879]} scale={100} />
          <mesh geometry={nodes.Cylinder002_Material001_0.geometry} material={materials['Material.001']} position={[-169.357, 160.13, -33.541]} rotation={[-2.36, -0.233, -2.299]} scale={100} />
          <mesh geometry={nodes.Spiral_metal001_0.geometry} material={materials['metal.001']} position={[-7.496, 54.684, -192.247]} rotation={[2.555, 0.704, -1.879]} scale={[34.992, 31.771, 31.771]} />
        </group>
      </group>
    </group>
  )
})

Dumbbell.displayName = 'Dumbbell'

useGLTF.preload('/models/hero/dumbbell.glb')
