/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 football.glb 
Author: Armellino Raffaele (https://sketchfab.com/armellino.raffaele)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/adidas-teamgeist-ball-germany-2006-match-ball-570b82c4391c49ddb1e471e6e55de9f4
Title: Adidas Teamgeist Ball (Germany 2006 Match Ball)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
// import * as THREE from 'three'

export function Football(props) {
  const { nodes, materials } = useGLTF('/models/hero/football.glb')

  // materials.Ball_Triangles.emissive = new THREE.Color(0x00f)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Ball_Triangles} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Ball_Ovals} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Ball_Ovals} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/hero/football.glb')
