/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 spiderman.glb 
Author: Neut2000 (https://sketchfab.com/Neut2000)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lego-spiderman-minifigure-version-2-2010edbfc0a34201b659655539b33953
Title: Lego Spiderman minifigure version 2
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Spiderman(props) {
  const { scene } = useGLTF('/models/spiderman.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group position={[0.004, 1.41, 0.029]}>
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh geometry={nodes.Object_12.geometry} material={materials.lego} skeleton={nodes.Object_12.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/spiderman.glb')
