/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ttflag.glb 
*/

import React, { useRef, useState, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
export function Ttflag(props) {
  const { nodes, materials } = useGLTF("/models/hero/ttflag.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
     
    </group>
  )
}

useGLTF.preload("/models/hero/ttflag.glb");
