/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ttflag.glb
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import type { ThreeElements } from '@react-three/fiber'
import { assetsPaths } from '../../constants';

type GroupProps = ThreeElements['group'];

type GLTFResult = {
  nodes: Record<string, THREE.Mesh>;
  materials: Record<string, THREE.MeshStandardMaterial>;
};

export function Ttflag(props: GroupProps) {
  const { nodes } = useGLTF(assetsPaths.models.hero.ttflag) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />

    </group>
  )
}

useGLTF.preload(assetsPaths.models.hero.ttflag);
